name: Das-Global
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75026
title: DAS GLOBAL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71664199-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15669e'
    - '#00243e'
    - '#d7eefe'
    - '#4e9fd7'
    - '#72c3fb'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
