name: Das-Global
favicon: null
layout_spectrum: 0.6833593973424286
typography_spectrum: 0.05550899961963296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15669e'
    - '#00243e'
    - '#d7eefe'
    - '#4e9fd7'
    - '#72c3fb'
  brandStrength: 0.5
  lightness: 0.5012600142508745
  saturation: 0.4396446228493005
  rhythmicContrast: 0.6126005235128105
purpose: []
